// Code generated by ogen, DO NOT EDIT.
package outline

type AccessKeysIDDataLimitDeleteRes interface {
	accessKeysIDDataLimitDeleteRes()
}

type AccessKeysIDDataLimitPutRes interface {
	accessKeysIDDataLimitPutRes()
}

type AccessKeysIDDeleteRes interface {
	accessKeysIDDeleteRes()
}

type AccessKeysIDGetRes interface {
	accessKeysIDGetRes()
}

type AccessKeysIDNamePutRes interface {
	accessKeysIDNamePutRes()
}

type ExperimentalAccessKeyDataLimitPutRes interface {
	experimentalAccessKeyDataLimitPutRes()
}

type ExperimentalAsnMetricsEnabledPutRes interface {
	experimentalAsnMetricsEnabledPutRes()
}

type MetricsEnabledPutRes interface {
	metricsEnabledPutRes()
}

type NamePutRes interface {
	namePutRes()
}

type ServerAccessKeyDataLimitPutRes interface {
	serverAccessKeyDataLimitPutRes()
}

type ServerHostnameForAccessKeysPutRes interface {
	serverHostnameForAccessKeysPutRes()
}

type ServerPortForNewAccessKeysPutRes interface {
	serverPortForNewAccessKeysPutRes()
}
