// Code generated by ogen, DO NOT EDIT.

package outline

// AccessKeysIDDataLimitDeleteParams is parameters of DELETE /access-keys/{id}/data-limit operation.
type AccessKeysIDDataLimitDeleteParams struct {
	// The id of the access key.
	ID string
}

// AccessKeysIDDataLimitPutParams is parameters of PUT /access-keys/{id}/data-limit operation.
type AccessKeysIDDataLimitPutParams struct {
	// The id of the access key.
	ID string
}

// AccessKeysIDDeleteParams is parameters of DELETE /access-keys/{id} operation.
type AccessKeysIDDeleteParams struct {
	// The id of the access key to delete.
	ID string
}

// AccessKeysIDGetParams is parameters of GET /access-keys/{id} operation.
type AccessKeysIDGetParams struct {
	// The id to get the access key.
	ID string
}

// AccessKeysIDNamePutParams is parameters of PUT /access-keys/{id}/name operation.
type AccessKeysIDNamePutParams struct {
	// The id of the access key to rename.
	ID string
}

// AccessKeysIDPutParams is parameters of PUT /access-keys/{id} operation.
type AccessKeysIDPutParams struct {
	// The id for which to create an access key.
	ID string
}
